domain: cli
language: python
project_slug: system_intelligence
template_version: '1.2.1 # <<COOKIETEMPLE_NO_BUMP>>'
template_handle: cli-python
github_username: zethson
is_github_repo: true
is_repo_private: false
is_github_orga: true
full_name: Lukas Heumos
email: lukas.heumos@posteo.net
project_name: system-intelligence
project_short_description: Query your system for all hardware and software related
  information.
version: 1.2.1
license: Apache2.0
command_line_interface: Click
testing_library: pytest
