name: PR to master branch from PATCH/release branch only

on:
  pull_request:
    branches:
    - master

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - name: Check if PR branch to master is PATCH or release branch
        run: |
            branch=$(echo "${{ github.event.pull_request.head.ref }}" | tr '[:upper:]' '[:lower:]')
            echo "Pull request's branch to be merged is: ${{ github.event.pull_request.head.ref  }}"
            if [[ "$branch" != *"patch"* ]] && [[ "$branch" != *"release"* ]]; then echo "PRs only from patch or release branch to master"; exit 1; fi
